version: "3.7"
services:
  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=iverbs
      - MYSQL_DATABASE=ivapi_1
    # ports:
    #   - 3307:3306
  api:
    build:
      context: .
      target: dev
    depends_on:
      - redis
      - mysql
    environment:
      - MIGRATIONS_PATH=/go/pkg/mod/github.com/noisyscanner/gofly@v1.0.0/migrations
    volumes:
      - .:/go/src/bradreed.co.uk/iverbs/api
