version: "3.7"
services:
  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=iverbs
      - MYSQL_DATABASE=ivapi_1
    ports:
      - 3307:3306
    networks:
      - ivapi_internal
  api:
    image: ivapi_api:dev
    build:
      context: .
      target: dev
    depends_on:
      - redis
      - mysql
    environment:
      - DB_USER=root
      - DB_PASS=iverbs
      - DB_NAME=ivapi_1
      - MIGRATIONS_PATH=/go/pkg/mod/github.com/noisyscanner/gofly@v1.0.3/migrations
    volumes:
      - .:/go/src/github.com/noisyscanner/ivapi
