version: "3.7"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - ivapi_bridge
  api:
    build:
      context: .
    depends_on:
      - redis
    environment:
      - DB_HOST=${DB_HOST:-mysql}
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS:-iverbs}
      - DB_NAME=${DB_NAME:-ivapi_1}
      - REDIS=redis:6379
      - PORT=7000
      - CACHE_DIRECTORY=${CACHE_DIRECTORY:-/var/ivapi/langcache}
    ports:
      - 7000:7000
    networks:
      - ivapi_bridge
    volumes:
      - ${CACHE_DIRECTORY_HOST}:${CACHE_DIRECTORY:-/var/ivapi/langcache}
networks:
  ivapi_bridge:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ivapi-bridge
